### ISSUE TITLE
Unable to load fonts from web URL within fontCallback due to promise delay 

### ISSUE THREAD

**Issue by kliemohn** [alafr/SVG-to-PDFKit#119] opened 2020-04-29 21:32 UTC
I have seen samples of how to use fontCallback:

- [Issue 72](https://github.com/alafr/SVG-to-PDFKit/issues/72#issuecomment-379069077)
- In the source code itself (as it has its own implementation

However, for my implementation I need to load the fonts from a web resource.  As such I am using [fetch()](https://javascript.info/fetch) which returns a promise.  In doing so, the svg-to-pdfkit complains because I haven't registered the font before exiting the fontCallback function.  Is there a way to return a promise from the fontCallback function instead?

**Comment by alafr** [comment] 2020-04-30 18:13
No, this is not possible with the current implementation. You can use the workaround described [here](https://github.com/alafr/SVG-to-PDFKit/issues/100#issuecomment-486347018).

Duplicate of #100

**Closed by alafr** 2020-04-30 18:13 UTC

**Comment by kliemohn** [comment] 2020-04-30 19:18
Thanks for the quick response and sorry for the duplicate!
